services:
  api:
    image: ghcr.io/alertua/styletts2-ukrainian-openai-tts-api:latest
    container_name: ${CONTAINER_PREFIX}api
    env_file:
      - .env
    ports:
      # host_port:container_port
      - ${UVICORN_PORT}:${UVICORN_PORT}

  gradio:
    image: ghcr.io/alertua/patriotyk_styletts2_ukrainian_docker:latest
    container_name: ${CONTAINER_PREFIX}gradio
    env_file:
      - .env
    ports:
      # host_port:container_port
      - ${GRADIO_SERVER_PORT}:${GRADIO_SERVER_PORT}
    volumes:
      - ${CACHE_PATH}/.cache:/usr/src/app/.cache
      - ${CACHE_PATH}/onnx:/usr/src/app/onnx

#    # uncomment this block to use the NVIDIA GPU
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
